<!-- Footer page -->
<!-- Author: xwang -->

<%@ taglib uri="http://java.sun.com/jsf/core" prefix="ff" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="fh" %>

<ff:subview id="footer">
   <table class="footerPage" width="100%" border=0 cellspacing=0>
      <tr><td>
         <hr width="100%" color="#3366CC"/></td>
      </td></tr>
      <tr><td>
         <div class="footerPageTitle">
            Generated by Sybase PowerDesigner.  <a href="http://www.sybase.com/powerdesigner">www.sybase.com/powerdesigner</a>
         </div>
      </td></tr>
   </table>
</ff:subview>