//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM_EF.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_TCategory
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> QCount { get; set; }
        public Nullable<int> Show1 { get; set; }
        public string Description { get; set; }
    }
}
