<?xml version="1.0" encoding="UTF-8"?>
<?PowerDesigner AppLocale="UTF16" Code="Document Type Definition" Family="DTD" HasExtendedMetaClass="FALSE" ID="{90310E42-214E-4024-AF2C-93E200C7A0DB}" LastModificationDate="1071582100" Name="Document Type Definition 1.0" Objects="96" Symbols="0" Type="{40249E0F-D7DA-41DC-8056-6199DCA3A7D8}" signature="XSL_XML" version="16.5.3.4276"?>
<!-- do not edit this file -->

<SchemaLanguage xmlns:a="attribute" xmlns:c="collection" xmlns:o="object">

<o:SchemaLanguage Id="o1">
<a:ObjectID>90310E42-214E-4024-AF2C-93E200C7A0DB</a:ObjectID>
<a:Name>Document Type Definition 1.0</a:Name>
<a:Code>Document Type Definition</a:Code>
<a:CreationDate>1054733461</a:CreationDate>
<a:Creator>fsaison</a:Creator>
<a:ModificationDate>1071582100</a:ModificationDate>
<a:Modifier>fhillard</a:Modifier>
<a:Family>DTD</a:Family>
<a:CheckGlobalScript>&#39;******************************************************************************
&#39;* Purpose:  This script holds global definitions shared by all the custom-
&#39;*            checks scripts of the model extension.
&#39;******************************************************************************

Option Explicit &#39; This is to ensure all used variables are defined

</a:CheckGlobalScript>
<c:Categories>
<o:ProfileTargetItem Id="o2">
<a:ObjectID>F9617A80-9679-41B2-BBD5-BC210B6B9C96</a:ObjectID>
<a:Name>Profile</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TargetCategory Id="o3">
<a:ObjectID>528DC089-9397-4D7B-9855-9D1BB05C891E</a:ObjectID>
<a:Name>Shared</a:Name>
<a:Code>Shared</a:Code>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TypedCategoryTargetItem Id="o4">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>3C7D1C75-D4DD-49DF-A9F3-A7A9FD209E77</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o5">
<a:ObjectID>6B00C77A-CB64-4CA7-B725-2E3E5A5FE3C8</a:ObjectID>
<a:Name>isMultiLine</a:Name>
<a:TemplateTargetItem.Value>.set_value(_isMultiLine, &quot;&quot;, new)
.foreach_line(%*@1%)
   .if (%_isMultiLine% == &quot;&quot;)
      .set_value(_isMultiLine, false)   
   .elsif (%_isMultiLine% == false)
      .set_value(_isMultiLine, true)   
   .endif
.next
%_isMultiLine%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o6">
<a:ObjectID>5293E283-7D6C-40AD-A6CE-45D88138C8AD</a:ObjectID>
<a:Name>commentDecl</a:Name>
<a:TemplateTargetItem.Value>.set_value(_commentValue, %*@1%, new)
.if (%.T:_commentValue%)
   .if (%isMultiLine(_commentValue)%)
&lt;!--
%_commentValue%
--&gt;
   .else
&lt;!-- %_commentValue% --&gt;
   .endif
.endif
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o7">
<a:ObjectID>0F811C1B-5AAD-43D6-B5A6-13AE95800727</a:ObjectID>
<a:Name>escapeE</a:Name>
<a:TemplateTargetItem.Value>.set_value(_XML, %.X:*@1%, new)
.if (%Folder%)
   .foreach_item(Folder.Entities,,,%Parameter% == false)
.set_value(_XML, %escapeE(_XML)%)
   .next
.else
   .foreach_item(Entities,,,%Parameter% == false)
.set_value(_XML, %escapeE(_XML)%)
   .next
.endif
%_XML%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:Comment>Escape entities</a:Comment>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o8">
<a:ObjectID>2EB4C9EB-B60A-4527-9ADB-093CF4D136CE</a:ObjectID>
<a:Name>escapePE</a:Name>
<a:TemplateTargetItem.Value>.set_value(_XML, %*@1%, new)
.set_value(_oid, %ObjectID%, new)
.if (%Folder%)
   .foreach_item(Folder.Entities,,,%Parameter%)
      .if (%ObjectType% != Entity) or (%Value% != %_XML%)
.set_value(_XML, %escapePE(_XML)%)
      .endif
   .next
.else
   .foreach_item(Entities,,,%Parameter%)
      .if (%ObjectType% != Entity) or (%Value% != %_XML%)
.set_value(_XML, %escapePE(_XML)%)
      .endif
   .next
.endif
%_XML%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:Comment>Escape parameter entities</a:Comment>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o9">
<a:ObjectID>96805494-EDE5-4779-94A3-DAA61A667B59</a:ObjectID>
<a:Name>hasQuote</a:Name>
<a:TemplateTargetItem.Value>.vbscript(%*@1%)
If (InStr(ScriptInputArray(0), &quot;&quot;&quot;&quot;)) Then
   ScriptResult = &quot;yes&quot;
Else
   ScriptResult = &quot;&quot;
End If
.endvbscript
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o10">
<a:ObjectID>F81C7F54-26F9-4A76-8F48-9DB1B95E496A</a:ObjectID>
<a:Name>escapePEName</a:Name>
<a:TemplateTargetItem.Value>.set_value(_Name, %*@1%, new)
.if (%Folder%)
   .foreach_item(Folder.Entities,,,%Parameter%)
      .if (%_Name% == %Value%)
.set_value(_Name, %%%Code%;)
      .endif
   .next
.else
   .foreach_item(Entities,,,%Parameter%)
      .if (%_Name% == %Value%)
.set_value(_Name, %%%Code%;)
      .endif
   .next
.endif
%_Name%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o11">
<a:ObjectID>D7BB1CFE-8093-429C-869B-F7478AD2248A</a:ObjectID>
<a:Name>escapeSimpleQuote</a:Name>
<a:TemplateTargetItem.Value>.replace(&quot;&#39;&quot;, &quot;&amp;#39;&quot;)
%*@1%
.endreplace</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:TargetCategory>
<o:MetaClassTargetItem Id="o12">
<a:ObjectID>FDE7BFC5-1FBC-41FB-9D2E-FDF6E070E46B</a:ObjectID>
<a:Name>Element</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:EnableSelectionGeneration>1</a:EnableSelectionGeneration>
<c:Categories>
<o:TypedCategoryTargetItem Id="o13">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>D817B4EC-FE6C-4D2E-A030-B8EA06F2FCB2</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o14">
<a:ObjectID>380D8681-54F1-4F5B-A7A9-F709D1CA8911</a:ObjectID>
<a:Name>markupDecl</a:Name>
<a:TemplateTargetItem.Value>.ifnot (%ReferenceName%)
%elementDecl%[
%attListDecl%]\n
.if (%Group%)
%Group.markupDecl%
.endif
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o15">
<a:ObjectID>2451712D-3490-4961-96A8-106A0C17FC83</a:ObjectID>
<a:Name>elementDecl</a:Name>
<a:TemplateTargetItem.Value>.if (%Comment%)
%commentDecl(Comment)%
.endif(\n)
&lt;!ELEMENT %escapePEName(Code)%[ %escapePE(contentSpec)%]&gt;</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o16">
<a:ObjectID>8C600F85-8794-48AB-AB3B-153CFFF79184</a:ObjectID>
<a:Name>contentSpec</a:Name>
<a:TemplateTargetItem.Value>.if (%hasAny%)
ANY
.elsif (%Group%) and (%TypeName%)
(#PCDATA|%Group.subItemUse%)*
.elsif (%TypeName%)
(#PCDATA)
.elsif (%Group%)
(%Group.subItemUse%)%Group.cardinality%
.else
EMPTY
.endif
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o17">
<a:ObjectID>34EE6185-6E05-4E9C-BE73-DEEC67B7C328</a:ObjectID>
<a:Name>attListDecl</a:Name>
<a:TemplateTargetItem.Value>.ifnot (%Attributes.IsEmpty%)
[%commentDecl(attComments)%\n]\
&lt;!ATTLIST %escapePEName(Code)%[ 
           %escapePE(attDecls)%]&gt;
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o18">
<a:ObjectID>83A8E17A-D5B4-4AD3-BBC9-C28D6F353F53</a:ObjectID>
<a:Name>attDecls</a:Name>
<a:TemplateTargetItem.Value>.foreach_item(Attributes,,\n)
%attDecl%
.next(\n)</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o19">
<a:ObjectID>D1512B62-3965-4266-A98F-6545B0F68F1A</a:ObjectID>
<a:Name>itemUse</a:Name>
<a:TemplateTargetItem.Value>.if (%ReferenceName%)
%ReferenceName%%cardinality%
.else
%Code%%cardinality%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o20">
<a:ObjectID>D26CB83A-B39B-4F18-A351-B6995CE3CF2E</a:ObjectID>
<a:Name>hasAny</a:Name>
<a:TemplateTargetItem.Value>.if (%Group%)
%Group.hasAny%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o21">
<a:ObjectID>CB96E1C1-14FC-4585-A305-EA1C1A551DA2</a:ObjectID>
<a:Name>attComments</a:Name>
<a:TemplateTargetItem.Value>.foreach_item(Attributes)
%attComment%
.next(\n\n)
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
<o:TypedCategoryTargetItem Id="o22">
<a:TypePublicName>GeneratedFileTargetItem</a:TypePublicName>
<a:ObjectID>622C760C-DE8D-4BEE-9B6A-5D7B56ECEC24</a:ObjectID>
<a:Name>Generated Files</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:GeneratedFileTargetItem Id="o23">
<a:ObjectID>5470D54C-C632-4209-9862-F7E9F876A178</a:ObjectID>
<a:Name>DTD File</a:Name>
<a:TemplateTargetItem.Value>.ifnot (%ReferenceName%)
%elementDecl%
%attListDecl%
.endif

</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:GeneratedFileTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o24">
<a:ObjectID>63ECA793-7CBE-48A8-8FDC-9BB0DCAB65D8</a:ObjectID>
<a:Name>Notation</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:EnableSelectionGeneration>1</a:EnableSelectionGeneration>
<c:Categories>
<o:TypedCategoryTargetItem Id="o25">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>B9AB1452-E795-4CA0-A548-9DCD078C463F</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o26">
<a:ObjectID>A24595A3-937D-4DBA-956B-9ADCDC1A06DA</a:ObjectID>
<a:Name>markupDecl</a:Name>
<a:TemplateTargetItem.Value>%notationDecl%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o27">
<a:ObjectID>19093394-F502-4089-97A8-E8EBAA7D047B</a:ObjectID>
<a:Name>notationDecl</a:Name>
<a:TemplateTargetItem.Value>.if (%Comment%)
%commentDecl(Comment)%
.endif(\n)
&lt;!NOTATION %escapePEName(Code)%
.if (%SystemURI%) and (%PublicURI%)
 PUBLIC &quot;%PublicURI%&quot; &quot;%SystemURI%&quot;
.elsif (%SystemURI%)
 SYSTEM &quot;%SystemURI%&quot;
.elsif (%PublicURI%)
 PUBLIC &quot;%PublicURI%&quot;
.endif
 &gt;</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
<o:TypedCategoryTargetItem Id="o28">
<a:TypePublicName>GeneratedFileTargetItem</a:TypePublicName>
<a:ObjectID>B703F35A-69B8-4837-9816-DA1FAAA69B0D</a:ObjectID>
<a:Name>Generated Files</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:GeneratedFileTargetItem Id="o29">
<a:ObjectID>83C129C6-799A-4380-85A0-ED173C0C2C8E</a:ObjectID>
<a:Name>DTD File</a:Name>
<a:TemplateTargetItem.Value>%notationDecl%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:GeneratedFileTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o30">
<a:ObjectID>14B5506F-6221-4F3A-AC1A-EE3A9D486131</a:ObjectID>
<a:Name>Attribute</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TypedCategoryTargetItem Id="o31">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>C0317BBE-54C0-4C4A-B8C8-12022BE756CD</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o32">
<a:ObjectID>47FD1228-9960-4DF9-8022-642456B9FF1D</a:ObjectID>
<a:Name>attDecl</a:Name>
<a:TemplateTargetItem.Value>.if (%Reference%)
%Reference.attDecl%
.else
%30:Code% %20:attType% %defaultDecl%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o33">
<a:ObjectID>7B7D93DA-8E71-40C5-AA0F-E7B129D40B0A</a:ObjectID>
<a:Name>attType</a:Name>
<a:TemplateTargetItem.Value>.if (%ListOfValues%)
%values%
.elsif (%TypeName%)
%TypeName%
.else
CDATA
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o34">
<a:ObjectID>0DBED536-C43C-415E-8995-9BFE677A7597</a:ObjectID>
<a:Name>defaultDecl</a:Name>
<a:TemplateTargetItem.Value>.if (%Use% == &quot;required&quot;)
#REQUIRED
.elsif (%Use% == &quot;optional&quot;)
#IMPLIED
.elsif (%FixedValue% != &quot;&quot;)
#FIXED &quot;%FixedValue%&quot;
.elsif (%DefaultValue% != &quot;&quot;)
&quot;%DefaultValue%&quot;
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o35">
<a:ObjectID>9FE2E976-FBD0-43E4-813F-FC882B827EC1</a:ObjectID>
<a:Name>attComment</a:Name>
<a:TemplateTargetItem.Value>.if (%Comment%)
%Code%:
%Comment%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o36">
<a:ObjectID>5AEF52C9-4C08-4A01-BF05-8AC7CFF1D513</a:ObjectID>
<a:Name>values</a:Name>
<a:TemplateTargetItem.Value>.foreach_line(%ListOfValues%, &quot;(&quot;, &quot;)&quot;)
   .set_value(_bFirstPart, true, new)
   .foreach_part(%CurrentLine%,&#39;\t&#39;)
      .if (%_bFirstPart%)
%CurrentPart%
      .endif
      .set_value(_bFirstPart, false)
   .next
.next(|)</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
<o:TypedCategoryTargetItem Id="o37">
<a:TypePublicName>CustomCheckTargetItem</a:TypePublicName>
<a:ObjectID>29A97226-F980-4C50-B327-C2C484C888FF</a:ObjectID>
<a:Name>Custom Checks</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:CustomCheckTargetItem Id="o38">
<a:ObjectID>F8E7398E-CFD2-4167-844E-B1957055C91D</a:ObjectID>
<a:Name>Incorrect attribute details</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:HelpMessage>This check ensures that either Default, or Fixed, or Use is specified for the attribute.</a:HelpMessage>
<a:OutputMessage>The details of the following attributes are incorrect:</a:OutputMessage>
<a:CheckScript>Function %Check%(obj)
   %Check% = True
   If not (obj is nothing) Then
      If (obj.ReferenceName = &quot;&quot;) and (obj.DefaultValue = &quot;&quot;) and (obj.Use = &quot;&quot;) and (obj.FixedValue = &quot;&quot;) Then
         %Check% = False
      End If
   End If
End Function</a:CheckScript>
<a:AutoFixScrpt>Function %Fix%(obj, outmsg)
   &#39; Implement your automatic correction on &lt;obj&gt; here
   &#39; filling &lt;outmsg&gt; as you wish
   &#39; and return True if successful.

   outmsg = &quot;Automatic correction not implemented&quot;

   %Fix% = False
End Function</a:AutoFixScrpt>
</o:CustomCheckTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o39">
<a:ObjectID>EB513AB8-D2A2-48B6-AFF1-D0271203B2D3</a:ObjectID>
<a:Name>AttributeGroup</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TypedCategoryTargetItem Id="o40">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>3314EE45-C745-4F32-B61C-25FB348D46AD</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o41">
<a:ObjectID>F804BEC9-8ABF-438C-B287-A05F62641974</a:ObjectID>
<a:Name>attDecl</a:Name>
<a:TemplateTargetItem.Value>.if (%Reference%)
%Reference.attDecl%
.else
   .foreach_item(Attributes)
%attDecl%
   .next(\n)
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o42">
<a:ObjectID>AAB9A37C-7514-4D51-9DF8-63AD53AD99F1</a:ObjectID>
<a:Name>attComment</a:Name>
<a:TemplateTargetItem.Value>.if (%Reference%)
%Reference.attComment%
.else
   .foreach_item(Attributes)
%attComment%
   .next(\n\n)
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o43">
<a:ObjectID>45429311-4D69-47E3-A1BD-46BE482823DF</a:ObjectID>
<a:Name>GroupParticle</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TypedCategoryTargetItem Id="o44">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>78D00659-9349-4590-9DFA-D5D05716B3F2</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o45">
<a:ObjectID>858F83CA-D9BE-4750-842B-39CE886CE4BD</a:ObjectID>
<a:Name>itemUse</a:Name>
<a:TemplateTargetItem.Value>.set_value(_use, %subItemUse%, new)
.if (%_use%)
(%_use%)%cardinality%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o46">
<a:ObjectID>2C36ED54-8D74-41A3-88EC-B31599150D26</a:ObjectID>
<a:Name>subItemUse</a:Name>
<a:TemplateTargetItem.Value>.if (%GroupType% == choice)
.foreach_item(Items)
%itemUse%
.next(|)
.else
.foreach_item(Items)
%itemUse%
.next(,)
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o47">
<a:ObjectID>A8727E1B-6BCF-4491-9409-B0BD2E93F347</a:ObjectID>
<a:Name>markupDecl</a:Name>
<a:TemplateTargetItem.Value>.foreach_item(Items,,\n)
%markupDecl%
.next(\n)
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o48">
<a:ObjectID>06E45E93-1C25-4074-8D29-C508BA7865C7</a:ObjectID>
<a:Name>hasAny</a:Name>
<a:TemplateTargetItem.Value>.foreach_item(Items)
   .if (%ObjectType% == Any)
true
   .elsif ((%ObjectType% == Group) or (%ObjectType% == GroupParticle))
%hasAny%   
   .endif
.next</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o49">
<a:ObjectID>AFE314B1-5675-4B41-A76F-550B2C6C01C3</a:ObjectID>
<a:Name>Particle</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TypedCategoryTargetItem Id="o50">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>013B8769-9868-4973-83A6-0203317CA17E</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o51">
<a:ObjectID>217D7CD6-A4B2-4928-8079-937F682360D0</a:ObjectID>
<a:Name>cardinality</a:Name>
<a:TemplateTargetItem.Value>.if ( ((%MinOccurs% == &quot;&quot;) or(%MinOccurs% &gt;= 1)) and ((%MaxOccurs% == unbounded) or (%MaxOccurs% &gt; 1)))
+
.elsif ((%MaxOccurs% == unbounded) or (%MaxOccurs% &gt; 1))
*
.elsif (%MinOccurs% == 0)
?
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o52">
<a:ObjectID>840A5726-6D61-4BCC-84D6-D4500BEE89C4</a:ObjectID>
<a:Name>Group</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TypedCategoryTargetItem Id="o53">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>E633F892-5696-4185-B476-E4B67F349F28</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o54">
<a:ObjectID>5BCB7D05-90D8-4B44-9F86-C260AA532FDF</a:ObjectID>
<a:Name>itemUse</a:Name>
<a:TemplateTargetItem.Value>.if (%Reference%)
%Reference.subItemUse%%cardinality%
.elsif (%GroupParticle%)
%GroupParticle.itemUse%%cardinality%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o55">
<a:ObjectID>BF99CA78-D915-4CE0-A14E-435202E22EEF</a:ObjectID>
<a:Name>subItemUse</a:Name>
<a:TemplateTargetItem.Value>.if (%Reference%)
%Reference.subItemUse%
.elsif (%GroupParticle%)
%GroupParticle.subItemUse%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o56">
<a:ObjectID>54C97D65-6CF7-45C9-BC7A-325A2F798840</a:ObjectID>
<a:Name>markupDecl</a:Name>
<a:TemplateTargetItem.Value>.ifnot (%Reference%)
.if (%GroupParticle%)
%GroupParticle.markupDecl%
.endif(\n)
.endif(\n)</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o57">
<a:ObjectID>7750F9F6-68A1-4D15-859A-F626CADB1E05</a:ObjectID>
<a:Name>hasAny</a:Name>
<a:TemplateTargetItem.Value>.if (%Reference%)
%Reference.hasAny%
.elsif (%GroupParticle%)
%GroupParticle.hasAny%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o58">
<a:ObjectID>9A6BBC53-A7B7-46DB-AFDA-21421768F0CF</a:ObjectID>
<a:Name>Extension</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o59">
<a:ObjectID>E4806983-DE4D-45A3-8DC2-1FAA8A29F69D</a:ObjectID>
<a:Name>Restriction</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o60">
<a:ObjectID>DF5B74AD-7BEE-4A78-BCBE-6AB33A65BE58</a:ObjectID>
<a:Name>SimpleTypeList</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o61">
<a:ObjectID>69A08D64-EEC9-4589-A963-0F8AA420F280</a:ObjectID>
<a:Name>SimpleTypeUnion</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o62">
<a:ObjectID>ABAD9413-463E-4307-A162-85D0341435D5</a:ObjectID>
<a:Name>Import</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o63">
<a:ObjectID>7D7F45E0-4A86-4BE3-AE91-272AD38970E3</a:ObjectID>
<a:Name>Include</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o64">
<a:ObjectID>99A67B22-6E5F-4CEE-AB8B-C099F4141AF6</a:ObjectID>
<a:Name>Redefine</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o65">
<a:ObjectID>531C27B3-ABB9-456B-A47B-3359E417118C</a:ObjectID>
<a:Name>Field</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o66">
<a:ObjectID>17115CCC-2C07-450F-9A16-CDAB5E1C6CE1</a:ObjectID>
<a:Name>Key</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o67">
<a:ObjectID>72495EBA-5BAD-430B-8025-E4BCF76A7BAC</a:ObjectID>
<a:Name>KeyRef</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o68">
<a:ObjectID>85A44CAD-770D-4139-B0BC-933956A8FE01</a:ObjectID>
<a:Name>Unique</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o69">
<a:ObjectID>44FF04BD-86A6-436A-91D9-5D7BB34ED0C1</a:ObjectID>
<a:Name>Selector</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o70">
<a:ObjectID>C86280F4-A161-42EB-B904-471343988D69</a:ObjectID>
<a:Name>ComplexType</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o71">
<a:ObjectID>D0A8EF36-6ECC-4A6A-A236-2BD8A7802417</a:ObjectID>
<a:Name>SimpleType</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o72">
<a:ObjectID>83D690B1-D95D-47FE-8DDB-90E5826F6C5A</a:ObjectID>
<a:Name>Annotation</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o73">
<a:ObjectID>F0BCE447-DE3A-417A-9559-449701177022</a:ObjectID>
<a:Name>Documentation</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o74">
<a:ObjectID>845B1B62-96AC-4DCD-9637-36FD1D5A0C2D</a:ObjectID>
<a:Name>Model</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:EnableSelectionGeneration>1</a:EnableSelectionGeneration>
<c:Categories>
<o:TypedCategoryTargetItem Id="o75">
<a:TypePublicName>GeneratedFileTargetItem</a:TypePublicName>
<a:ObjectID>29B39464-2634-4C7C-91EA-1283CB541596</a:ObjectID>
<a:Name>Generated Files</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:GeneratedFileTargetItem Id="o76">
<a:ObjectID>205C136B-6DB6-4BDC-BC10-B00FC1AB4189</a:ObjectID>
<a:Name>DTD File</a:Name>
<a:TemplateTargetItem.Value>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;\n
.if (%Comment%)
%commentDecl(Comment)%\n
.endif(\n)

.foreach_item(Entities,,\n)
%markupDecl%
.next(\n)
.foreach_item(Items)
.if (%ObjectType% == Element)
%markupDecl%
.elsif (%ObjectType% == Notation)
%markupDecl%
.elsif (%ObjectType% == Group)
%markupDecl%
.endif
.next(\n)
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:Filename>%fileName%</a:Filename>
<a:GeneratedFileTargetItem.Encoding>UTF-8</a:GeneratedFileTargetItem.Encoding>
</o:GeneratedFileTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
<o:TypedCategoryTargetItem Id="o77">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>B9BD17F9-A3CA-49B5-B554-3513736FB5AC</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o78">
<a:ObjectID>022E9E4A-035B-415C-9260-2B64431DA14C</a:ObjectID>
<a:Name>fileName</a:Name>
<a:TemplateTargetItem.Value>%Code%.dtd</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:Comment>compute the generated filename.</a:Comment>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o79">
<a:ObjectID>F86FBD99-C3F9-45A6-9003-64E88BF80395</a:ObjectID>
<a:Name>Any</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TypedCategoryTargetItem Id="o80">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>A4A7D3AA-886C-4179-9F71-B6E0DA19BD65</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o81">
<a:ObjectID>73A5B36B-D3F5-459B-8ADF-B85484C6402A</a:ObjectID>
<a:Name>markupDecl</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o82">
<a:ObjectID>80FCB9E9-1531-4990-8643-BD0F58258B71</a:ObjectID>
<a:Name>Entity</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:EnableSelectionGeneration>1</a:EnableSelectionGeneration>
<c:Categories>
<o:TypedCategoryTargetItem Id="o83">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>9FE081D6-DE44-4E8C-B6AA-487A4B3F7320</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o84">
<a:ObjectID>D3B7163E-FABE-4912-B3C2-D16B39C5A3D4</a:ObjectID>
<a:Name>markupDecl</a:Name>
<a:TemplateTargetItem.Value>%entityDecl%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o85">
<a:ObjectID>F09FBB23-0AE3-4F5C-AD72-841917EFBC99</a:ObjectID>
<a:Name>entityDecl</a:Name>
<a:TemplateTargetItem.Value>.if (%Comment%)
%commentDecl(Comment)%
.endif(\n)
&lt;!ENTITY[%Parameter%? %] %Code%
.if (%Value%)
   .if (%Value% == %.T:Value%)
      .set_value(_escapedValue, %::escapePE(Value)%, new)
   .else
      .set_value(_escapedValue, %Value%, new)
   .endif
   .if (%hasQuote(_escapedValue)%)
 &#39;%escapeSimpleQuote(_escapedValue)%&#39;
   .else
 &quot;%_escapedValue%&quot;
   .endif
.elsif (%SystemURI%)
 .if (%PublicURI%)
 PUBLIC &quot;%PublicURI%&quot; &quot;%SystemURI%&quot;
 .else
 SYSTEM &quot;%SystemURI%&quot;
 .endif
 .if (%NotationName%)
 NDATA %escapePEName(NotationName)%
 .endif
.endif
&gt;</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o86">
<a:ObjectID>01EA07CF-7EA8-4BE4-A318-97F26716048E</a:ObjectID>
<a:Name>escapeE</a:Name>
<a:TemplateTargetItem.Value>.if (%Value%)
   .replace(%Value%, &amp;%Code%;)
%*@1%
   .endreplace
.else
%*@1%
.endif
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o87">
<a:ObjectID>A2A5DCA6-37FD-46E1-92F5-0AFB146E161C</a:ObjectID>
<a:Name>escapePE</a:Name>
<a:TemplateTargetItem.Value>.if (%Value%)
   .replace(%Value%, %%%Code%;)
%*@1%
   .endreplace
.else
%*@1%
.endif
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
<o:TypedCategoryTargetItem Id="o88">
<a:TypePublicName>GeneratedFileTargetItem</a:TypePublicName>
<a:ObjectID>FA0EBCB1-6928-4239-96BA-5045CF8A05D5</a:ObjectID>
<a:Name>Generated Files</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:GeneratedFileTargetItem Id="o89">
<a:ObjectID>95136AB5-64E3-4A47-A6AC-10920BAE9D40</a:ObjectID>
<a:Name>DTD File</a:Name>
<a:TemplateTargetItem.Value>%entityDecl%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:GeneratedFileTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o90">
<a:ObjectID>0A2A6207-7A70-4A45-B1B9-F1B33FD5825E</a:ObjectID>
<a:Name>AnyAttribute</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
</c:Categories>
</o:ProfileTargetItem>
<o:TargetCategory Id="o91">
<a:ObjectID>3B4E864F-A332-47A5-B925-45B443414A6D</a:ObjectID>
<a:Name>Settings</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TargetCategory Id="o92">
<a:ObjectID>56E6825F-DB30-4785-A191-FB6EAAF949A3</a:ObjectID>
<a:Name>DataTypes</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:MapTargetItem Id="o93">
<a:ObjectID>AB3635F9-71EC-49BC-83BD-3A59744C1188</a:ObjectID>
<a:Name>ConceptualDataTypes</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:Comment>Conceptual Data Types</a:Comment>
<a:MapTargetItem.Value>A%n=CDATA
VA%n=CDATA
LA=CDATA
LA%n=CDATA
LVA=CDATA
LVA%n=CDATA
BT=CDATA
BT%n=CDATA
SI=CDATA
I=CDATA
LI=CDATA
N=CDATA
N%n=CDATA
N%s,%p=CDATA
DC=CDATA
DC%n=CDATA
DC%s,%p=CDATA
SF=CDATA
F=CDATA
F%n=CDATA
LF=CDATA
MN=CDATA
MN%n=CDATA
MN%s,%p=CDATA
D=CDATA
T=CDATA
DT=CDATA
TS=CDATA
BL=CDATA
NO=CDATA
NO%n=CDATA
BIN=CDATA
BIN%n=CDATA
LBIN=CDATA
LBIN%n=CDATA
TXT=CDATA
TXT%n=CDATA
MBT=CDATA
MBT%n=CDATA
VMBT=CDATA
VMBT%n=CDATA
PIC=CDATA
PIC%n=CDATA
BMP=CDATA
BMP%n=CDATA
OLE=CDATA
OLE%n=CDATA
ANY=CDATA
*=CDATA</a:MapTargetItem.Value>
<a:List>A%n
VA%n
LA
LA%n
LVA
LVA%n
BT
BT%n
SI
I
LI
N
N%n
N%s,%p
DC
DC%n
DC%s,%p
SF
F
F%n
LF
MN
MN%n
MN%s,%p
D
T
DT
TS
BL
NO
NO%n
BIN
BIN%n
LBIN
LBIN%n
TXT
TXT%n
MBT
MBT%n
VMBT
VMBT%n
PIC
PIC%n
BMP
BMP%n
OLE
OLE%n
ANY
</a:List>
</o:MapTargetItem>
<o:MapTargetItem Id="o94">
<a:ObjectID>F2B89121-54FF-4511-A7D7-2CAB168430BD</a:ObjectID>
<a:Name>XsmDataTypes</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:Comment>XSM Data Types</a:Comment>
<a:MapTargetItem.Value>CDATA=TXT
ID=TXT
IDREF=TXT
IDREFS=TXT
ENTITY=TXT
ENTITIES=TXT
NMTOKEN=TXT
NMTOKENS=TXT</a:MapTargetItem.Value>
<a:List>CDATA
ID
IDREF
IDREFS
ENTITY
ENTITIES
NMTOKEN
NMTOKENS
</a:List>
</o:MapTargetItem>
</c:Categories>
</o:TargetCategory>
<o:BooleanTargetItem Id="o95">
<a:ObjectID>8795C185-3A13-43C4-9849-D04A5CA1DCF5</a:ObjectID>
<a:Name>ElementUniqueCode</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:Comment>Unique code for elements</a:Comment>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:Value>1</a:Value>
</o:BooleanTargetItem>
</c:Categories>
</o:TargetCategory>
</c:Categories>
</o:SchemaLanguage>

</SchemaLanguage>