<?xml version="1.0" encoding="UTF-8"?>
<?PowerDesigner AppLocale="UTF16" Code="XML-Data Reduced" Family="XDR" HasExtendedMetaClass="FALSE" ID="{93ADC5C4-4375-4CF3-9E62-4B0A7B99A4F9}" LastModificationDate="1064403315" Name="XML-Data Reduced 1.0" Objects="93" Symbols="0" Type="{40249E0F-D7DA-41DC-8056-6199DCA3A7D8}" signature="XSL_XML" version="16.5.3.4276"?>
<!-- do not edit this file -->

<SchemaLanguage xmlns:a="attribute" xmlns:c="collection" xmlns:o="object">

<o:SchemaLanguage Id="o1">
<a:ObjectID>93ADC5C4-4375-4CF3-9E62-4B0A7B99A4F9</a:ObjectID>
<a:Name>XML-Data Reduced 1.0</a:Name>
<a:Code>XML-Data Reduced</a:Code>
<a:CreationDate>1063010981</a:CreationDate>
<a:Creator>fhillard</a:Creator>
<a:ModificationDate>1064403315</a:ModificationDate>
<a:Modifier>fhillard</a:Modifier>
<a:Family>XDR</a:Family>
<a:CheckGlobalScript>&#39;******************************************************************************
&#39;* Purpose:  This script holds global definitions shared by all the custom-
&#39;*            checks scripts of the model extension.
&#39;******************************************************************************

Option Explicit &#39; This is to ensure all used variables are defined

</a:CheckGlobalScript>
<c:Categories>
<o:TargetCategory Id="o2">
<a:ObjectID>266CC47B-9868-4903-80B2-19233C05D305</a:ObjectID>
<a:Name>Generation</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<c:Categories>
<o:TypedCategoryTargetItem Id="o3">
<a:TypePublicName>GenerationOptionTargetItem</a:TypePublicName>
<a:ObjectID>A3F33FA4-26D6-40E2-B2F6-BD3C6BAA637C</a:ObjectID>
<a:Name>Options</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:GenerationOptionTargetItem Id="o4">
<a:ObjectID>835C4A4E-3EFB-4098-9C6F-0654C55D93A1</a:ObjectID>
<a:Name>generateComments</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:Comment>Comments generation</a:Comment>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:BoolValue>1</a:BoolValue>
</o:GenerationOptionTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:TargetCategory>
<o:ProfileTargetItem Id="o5">
<a:ObjectID>125420B4-1894-46E7-9002-0C2031E33F7F</a:ObjectID>
<a:Name>Profile</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TargetCategory Id="o6">
<a:ObjectID>EDEAD217-E322-4A18-BDFB-7629F1028095</a:ObjectID>
<a:Name>Shared</a:Name>
<a:Code>Shared</a:Code>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TypedCategoryTargetItem Id="o7">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>BBDB20AC-084D-490A-B996-2575345D45A2</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o8">
<a:ObjectID>95362769-BFFD-45F2-B3C3-7DAD62A25761</a:ObjectID>
<a:Name>getXdrPrefix</a:Name>
<a:TemplateTargetItem.Value>.vbscript()
Dim sPrefix
sPrefix = ActiveModel.GetNamespacePrefix(&quot;urn:schemas-microsoft-com:xml-data&quot;)
if (sPrefix &lt;&gt; &quot;&quot;) then
   ScriptResult = sPrefix + &quot;:&quot;
end if
.endvbscript</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o9">
<a:ObjectID>720E711E-A3AE-438E-8023-B31404F6F853</a:ObjectID>
<a:Name>getXdrDttpPrefix</a:Name>
<a:TemplateTargetItem.Value>.vbscript()
Dim sPrefix
sPrefix = ActiveModel.GetNamespacePrefix(&quot;urn:schemas-microsoft-com:datatypes&quot;)
if (sPrefix &lt;&gt; &quot;&quot;) then
   ScriptResult = sPrefix + &quot;:&quot;
end if
.endvbscript</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
<o:TypedCategoryTargetItem Id="o10">
<a:TypePublicName>ExtendedAttributeTypeTargetItem</a:TypePublicName>
<a:ObjectID>C55CD71D-299C-4099-8CA3-353D31961610</a:ObjectID>
<a:Name>Extended Attribute Types</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:ExtendedAttributeTypeTargetItem Id="o11">
<a:ObjectID>D0BBC670-C854-4AC0-8D6D-2F2168D96849</a:ObjectID>
<a:Name>ElementTypeModelType</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:Comment>model attribute of an ElementType can have two different values: &quot;open&quot; or &quot;closed&quot;.</a:Comment>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExtendedAttributeTypeTargetItem.ListOfValues>open
closed</a:ExtendedAttributeTypeTargetItem.ListOfValues>
</o:ExtendedAttributeTypeTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:TargetCategory>
<o:MetaClassTargetItem Id="o12">
<a:ObjectID>EB4E5476-38D7-467C-B073-2BFCA10C3676</a:ObjectID>
<a:Name>Attribute</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:EnableSelectionGeneration>1</a:EnableSelectionGeneration>
<c:Categories>
<o:TypedCategoryTargetItem Id="o13">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>84950552-9D1A-4FA9-8279-59F42EFF1D72</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o14">
<a:ObjectID>6384D50E-E541-44AF-8403-9A03DFD0731E</a:ObjectID>
<a:Name>extendedAttributesType</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o15">
<a:ObjectID>B66F59CF-6F72-4641-AB83-8775013BEE7A</a:ObjectID>
<a:Name>attributeDeclaration</a:Name>
<a:TemplateTargetItem.Value>.// Generate attribute declarations
.if (%ReferenceName%)
.// case of an attribute reference
&lt;%xdrPrefix%attribute[ default=&quot;%DefaultValue%&quot;][ type=&quot;%ReferenceName%&quot;][ %extendedAttributes%]
.//if there is a comment for this attribute reference then it is written at the end with an end tag, 
.//otherwise, a simple end tag id added
   .if (%description%)
&gt;
   %description%
&lt;/%xdrPrefix%attribute&gt;
   .else
/&gt;
   .endif
.else
.// Generate an attribute (in this case it is a local one), it also generate his type declaration.
%attributeTypeDeclaration%
&lt;%xdrPrefix%attribute[ default=&quot;%DefaultValue%&quot;][ type=&quot;%Code%&quot;][ %extendedAttributes%]/&gt;
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o16">
<a:ObjectID>5ED9EC7E-652B-4491-8C9D-F39B46748494</a:ObjectID>
<a:Name>description</a:Name>
<a:TemplateTargetItem.Value>.if (%Comment%) and (%GenOptions.generateComments%)
&lt;%xdrPrefix%description&gt;%.AX:Comment%&lt;/%xdrPrefix%description&gt;
.endif
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o17">
<a:ObjectID>CE8E3D3E-08FA-4F3F-958A-6199CFCE7D54</a:ObjectID>
<a:Name>values</a:Name>
<a:TemplateTargetItem.Value>.foreach_line(%ListOfValues%)
   .set_value(_bFirstPart, true, new)
   .foreach_part(%CurrentLine%, &#39;\t&#39;)
      .if (%_bFirstPart%)
%CurrentPart%
      .endif
      .set_value(_bFirstPart, false)
   .next
.next(&quot; &quot;)</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o18">
<a:ObjectID>A1DA5DFB-0DC7-475F-B3C9-64BC3C1AD949</a:ObjectID>
<a:Name>extendedAttributes</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o19">
<a:ObjectID>5D3B2CEF-8AB0-42E5-A044-CF2D02B2A10F</a:ObjectID>
<a:Name>attributeTypeDeclaration</a:Name>
<a:TemplateTargetItem.Value>.// Generate the AttributeType and his own attributes like type, name, and default
&lt;%xdrPrefix%AttributeType[ name=&quot;%Code%&quot;][ default=&quot;%DefaultValue%&quot;][ dt:type=&quot;%TypeName%&quot;][ dt:values=&quot;%values%&quot;][ %extendedAttributesType%]
.// if there is a comment, then push it at the end with an end tag, otherwise simple end tag
.if (%description%)
&gt;
   %description%
&lt;/%xdrPrefix%AttributeType&gt;
.else
/&gt;
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
<o:TypedCategoryTargetItem Id="o20">
<a:TypePublicName>GeneratedFileTargetItem</a:TypePublicName>
<a:ObjectID>3F4A8FD2-8E2C-41FB-BAED-D0329B83D3BC</a:ObjectID>
<a:Name>Generated Files</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:GeneratedFileTargetItem Id="o21">
<a:ObjectID>5B4FBB08-4BD4-4A99-B6DD-55071CC1BF70</a:ObjectID>
<a:Name>XDR File</a:Name>
<a:TemplateTargetItem.Value>.set_value(xdrPrefix, %getXdrPrefix%, new)
%attributeTypeDeclaration%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:GeneratedFileTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o22">
<a:ObjectID>9A9A64AC-B435-4405-A8C9-E18377F112C5</a:ObjectID>
<a:Name>Element</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:EnableSelectionGeneration>1</a:EnableSelectionGeneration>
<c:Categories>
<o:TypedCategoryTargetItem Id="o23">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>B9AD8436-24F9-46C9-B7AC-8405A593432F</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o24">
<a:ObjectID>08888EAB-8107-4779-B7F6-7E8C08CD4773</a:ObjectID>
<a:Name>elementTypeDeclaration</a:Name>
<a:TemplateTargetItem.Value>.// template that generates ElementType entities
.ifnot (%ReferenceName%)
.// if it has a group, we generate all element types entities related to  the group
.if (%Group%)
%Group.elementTypeDeclaration%
.endif(\n)
&lt;%xdrPrefix%ElementType[ name=&quot;%Code%&quot;][ default=&quot;%DefaultValue%&quot;][ model=&quot;%model%&quot;][ %dataTypeContent%][ order=&quot;%order%&quot;][ dt:values=&quot;%values%&quot;][ %extendedAttributes%]
.// we assume that the required flag is not available in MSXML 4.0 (but it was in Microsoft XML 3.0) dumb !! 
.if (%isEmpty%)
.///&gt;
.// if there is a comment, it is inserted and end tag is pushed at the end, otherwise simple end tag
.ifnot (%description%)
/&gt;
.else
&gt;
[  %description%
]&lt;/%xdrPrefix%ElementType&gt;\n
.endif
.// if element not empty &gt; end tag is pushed at the end of line, and content is expanded
.else
.// comment of the ElementType and declarations of local attribute of this ElementType
&gt;
[   %description%
][   %attributeDeclarations%
]
.//expand the group reference with all elements included in the Group
.if (%Group%)
   %Group.itemReferences%
.endif(\n)
&lt;/%xdrPrefix%ElementType&gt;\n
.endif
.endif

</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o25">
<a:ObjectID>BA14ADE4-929F-4382-AEDA-B72E443F8E19</a:ObjectID>
<a:Name>attributeDeclarations</a:Name>
<a:TemplateTargetItem.Value>.// generates atribute declaration for each attributes of this element
.foreach_item(Attributes)
%attributeDeclaration%
.next(\n)</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o26">
<a:ObjectID>3B63795A-DF89-4FFA-9C10-5BAC6895A0E1</a:ObjectID>
<a:Name>order</a:Name>
<a:TemplateTargetItem.Value>.// return the type group is this element has a group as children (seq | one | many)
.if (%Group%)
%Group.groupType%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o27">
<a:ObjectID>9A50BD95-577D-4DD6-9620-2BBFB0C338D3</a:ObjectID>
<a:Name>itemReference</a:Name>
<a:TemplateTargetItem.Value>.// template that generates an element and his own attributes
&lt;%xdrPrefix%element[ type=&quot;%ReferenceName%&quot;][ type=&quot;%Code%&quot;][ minOccurs=&quot;%MinOccurs%&quot;][ %maxOccursTemplate%]
.// comment and end tag
.if (((%description%) and (%ReferenceName%)) or (%elementContent%))
&gt;
[   %description%
][   %elementContent%
]&lt;/%xdrPrefix%element&gt;
.else
/&gt;
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o28">
<a:ObjectID>8B42F673-413F-410A-A289-2363E7AA2E21</a:ObjectID>
<a:Name>isEmpty</a:Name>
<a:TemplateTargetItem.Value>.//return true if this element has no Attributes, otherwise return false
.if ((%Attributes.IsEmpty%) and (%Group% == null))
true
.else
false
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o29">
<a:ObjectID>D377B6ED-6146-49CE-A373-8BAE151FA600</a:ObjectID>
<a:Name>getmodel</a:Name>
<a:TemplateTargetItem.Value>.// We assume that if there is an Any element as child , 
.//the parent node is marked as an open model. By default this flag is set to closed.
.if (%AnyAttribute%)
open
.elsif (%Group%)
   .if (%Group.hasAny%)
open
   .else
closed
   .endif
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o30">
<a:ObjectID>D3B59E3A-F316-4515-8662-AB94C499BE80</a:ObjectID>
<a:Name>content</a:Name>
<a:TemplateTargetItem.Value>.// set up a flag to inform about the nature of content 
.if (%Group%) and (%TypeName%)
mixed
.elsif (%Group%)
eltOnly
.elsif (%TypeName%)
textOnly
.else
empty
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o31">
<a:ObjectID>5D457F69-077A-4207-9E0D-2B833A25176D</a:ObjectID>
<a:Name>description</a:Name>
<a:TemplateTargetItem.Value>.// Template generating comments for the description of the data
.if (%Comment%) and (%GenOptions.generateComments%)
&lt;%xdrPrefix%description&gt;%.AX:Comment%&lt;/%xdrPrefix%description&gt;
.endif
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o32">
<a:ObjectID>8D5C06F8-1D7C-4973-B76E-261EB5A1BDBC</a:ObjectID>
<a:Name>maxOccursTemplate</a:Name>
<a:TemplateTargetItem.Value>.if (%MaxOccurs%)
   .if (%MaxOccurs% == &quot;unbounded&quot;)
maxOccurs=&quot;*&quot;
   .else
maxOccurs=&quot;%MaxOccurs%&quot;
   .endif
.endif
   
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o33">
<a:ObjectID>738DBA94-33CF-423E-A882-E566D39BC5BE</a:ObjectID>
<a:Name>values</a:Name>
<a:TemplateTargetItem.Value>.foreach_line(%ListOfValues%)
   .set_value(_bFirstPart, true, new)
   .foreach_part(%CurrentLine%, &#39;\t&#39;)
      .if (%_bFirstPart%)
%CurrentPart%
      .endif
      .set_value(_bFirstPart, false)
   .next
.next(&quot; &quot;)</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o34">
<a:ObjectID>D1FC598E-B6A0-4D25-AD9B-7947269F8A87</a:ObjectID>
<a:Name>dataTypeContent</a:Name>
<a:TemplateTargetItem.Value>.if (%Group%) and (%Group.hasAny%) and (%Group.getNb% == 1)
content=&quot;empty&quot;[ dt:type=&quot;%TypeName%&quot;]
.elsif (%Group%) and (%TypeName%) 
content=&quot;mixed&quot;
.elsif (%Group%)
content=&quot;eltOnly&quot;
.elsif (%TypeName%)
[ dt:type=&quot;%TypeName%&quot;]
.else
content=&quot;empty&quot;
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o35">
<a:ObjectID>521E7333-007A-4A2A-B4D6-FF3180CFFC14</a:ObjectID>
<a:Name>extendedAttributes</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o36">
<a:ObjectID>4C7A8DDF-2A0B-4DAF-9EF2-7E05E394811D</a:ObjectID>
<a:Name>elementContent</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
<o:TypedCategoryTargetItem Id="o37">
<a:TypePublicName>GeneratedFileTargetItem</a:TypePublicName>
<a:ObjectID>12760B06-575C-4925-9943-ACF99177C122</a:ObjectID>
<a:Name>Generated Files</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:GeneratedFileTargetItem Id="o38">
<a:ObjectID>F036FB25-5EB9-41CB-9708-1EE68C0976C0</a:ObjectID>
<a:Name>XDR File</a:Name>
<a:TemplateTargetItem.Value>.set_value(xdrPrefix, %getXdrPrefix%, new)
%elementTypeDeclaration%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:GeneratedFileTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
<o:TypedCategoryTargetItem Id="o39">
<a:TypePublicName>ExtendedAttributeTargetItem</a:TypePublicName>
<a:ObjectID>3AB845EE-1FBB-45B1-A0FB-8BD2F30DB5E3</a:ObjectID>
<a:Name>Extended Attributes</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:ExtendedAttributeTargetItem Id="o40">
<a:ObjectID>525DBCA0-562F-468E-8EAC-5AAE9556D00F</a:ObjectID>
<a:Name>model</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:Comment>Two possible values for model attribute: &quot;open&quot; or &quot;closed&quot;.
If the element possess an Any attribute then the &quot;model&quot; attribute is set to &quot;open&quot;. Otherwise , it is set to &quot;closed&quot;.
</a:Comment>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExtendedAttributeTargetItem.DataType>-1</a:ExtendedAttributeTargetItem.DataType>
<a:ExtendedAttributeTargetItem.Value>%getmodel%</a:ExtendedAttributeTargetItem.Value>
<a:Template>1</a:Template>
<a:ValidateDataType>0</a:ValidateDataType>
<c:ExtendedAttributeType>
<o:ExtendedAttributeTypeTargetItem Ref="o11"/>
</c:ExtendedAttributeType>
</o:ExtendedAttributeTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o41">
<a:ObjectID>AF172742-3A2F-484F-BE53-F37E305BD25E</a:ObjectID>
<a:Name>Model</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:EnableSelectionGeneration>1</a:EnableSelectionGeneration>
<c:Categories>
<o:TypedCategoryTargetItem Id="o42">
<a:TypePublicName>GeneratedFileTargetItem</a:TypePublicName>
<a:ObjectID>C182477F-EFF9-42AE-A364-5F0344CADBD1</a:ObjectID>
<a:Name>Generated Files</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:GeneratedFileTargetItem Id="o43">
<a:ObjectID>46FE38A8-FA99-4666-8B2F-6E9C9B40ABF9</a:ObjectID>
<a:Name>XDR File</a:Name>
<a:TemplateTargetItem.Value>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;\n
.set_value(xdrPrefix, %getXdrPrefix%, new)
%schemaDeclaration%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:Filename>%fileName%</a:Filename>
<a:GeneratedFileTargetItem.Encoding>UTF-8</a:GeneratedFileTargetItem.Encoding>
</o:GeneratedFileTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
<o:TypedCategoryTargetItem Id="o44">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>CFC57D3A-49DA-4610-9A65-43294F19322C</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o45">
<a:ObjectID>60E9A131-1240-44A0-AE2D-7F91E98FBE6E</a:ObjectID>
<a:Name>schemaDeclaration</a:Name>
<a:TemplateTargetItem.Value>.// main rule for generating the XDR schema
&lt;%xdrPrefix%Schema[ name=&quot;%Code%&quot;][
%namespacesDecl%]&gt;[
.// commentaire associated to the schema
  %description%][
.// atribute types defined inside the model
  %attributeTypes%][
.// elements types defined in the model
  %elementTypes%]
&lt;/%xdrPrefix%Schema&gt;</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o46">
<a:ObjectID>3C221CC6-4B89-4F08-A458-D69F48DE3ABE</a:ObjectID>
<a:Name>attributeTypes</a:Name>
<a:TemplateTargetItem.Value>.//   Generate Attribute type declarations for each Attributes
.foreach_item(Attributes)
%attributeTypeDeclaration%
.next(\n)</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o47">
<a:ObjectID>6A4DEF09-EC44-4716-8CC3-1E7BA9F4EB73</a:ObjectID>
<a:Name>elementTypes</a:Name>
<a:TemplateTargetItem.Value>.foreach_item(Groups,,\n)
%elementTypeDeclaration%
.next(\n)
.foreach_item(Elements)
%elementTypeDeclaration%
.next(\n)

</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o48">
<a:ObjectID>72DB3486-7ECE-453F-AEE9-EBFD2F04AC6E</a:ObjectID>
<a:Name>description</a:Name>
<a:TemplateTargetItem.Value>.// The &quot;Comment&quot; edit box specifies a description associated to the model
.if (%Comment%) and (%GenOptions.generateComments%)
&lt;%xdrPrefix%description&gt;%.AX:Comment%&lt;/%xdrPrefix%description&gt;
.endif
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o49">
<a:ObjectID>D6D9B9C8-8832-4877-B8CF-FDAB81E0BC5D</a:ObjectID>
<a:Name>namespacesDecl</a:Name>
<a:TemplateTargetItem.Value>.unique
.ifnot (%getXdrPrefix%)
xmlns=&quot;urn:schemas-microsoft-com:xml-data&quot;
.endif(\n)
.ifnot (%getXdrDttpPrefix%)
xmlns=&quot;urn:schemas-microsoft-com:datatypes&quot;
.endif(\n)
.foreach_part(%Namespaces%, &quot;&#39;\n&#39;&quot;)
   .set_value(_uri, &quot;&quot;, new)
   .foreach_part(%CurrentPart%, &quot;&#39;\t&#39;&quot;)
      .if (%_uri% == &quot;&quot;)
         .set_value(_uri, %CurrentPart%)
      .else
xmlns[:%CurrentPart%]=&quot;%_uri%&quot;
         .set_value(_uri, &quot;&quot;)
      .endif
      .set_value(_bFirst, false)
   .next
      .if (%_uri%)
xmlns=&quot;%_uri%&quot;
   .endif
.next(\n) 
.endunique</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o50">
<a:ObjectID>EEC8BD44-7621-4926-AAC2-E2D919BCB94A</a:ObjectID>
<a:Name>fileName</a:Name>
<a:TemplateTargetItem.Value>%Code%.xdr</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
<o:TypedCategoryTargetItem Id="o51">
<a:TypePublicName>EventHandlerTargetItem</a:TypePublicName>
<a:ObjectID>95D94792-895A-4EE1-92BD-9BDC5EF61802</a:ObjectID>
<a:Name>Event Handlers</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:EventHandlerTargetItem Id="o52">
<a:ObjectID>ED9722C5-3EC4-4391-8F9D-65B5F04FFFB6</a:ObjectID>
<a:Name>Initialize</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:HandlerScript>Function %Initialize%(obj)
   &#39; Set the default namespace for XML Schema
   Dim sPrefix
   sPrefix = obj.GetNamespacePrefix(&quot;urn:schemas-microsoft-com:xml-data&quot;)
   if (sPrefix = &quot;&quot;) then
      obj.AddNamespace &quot;urn:schemas-microsoft-com:xml-data&quot;, &quot;&quot;
   end if
   sPrefix = obj.GetNamespacePrefix(&quot;urn:schemas-microsoft-com:datatypes&quot;)
   if (sPrefix = &quot;&quot;) then
      obj.AddNamespace &quot;urn:schemas-microsoft-com:datatypes&quot;, &quot;dt&quot;
   end if

   %Initialize% = True
End Function</a:HandlerScript>
</o:EventHandlerTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o53">
<a:ObjectID>63D8AEB2-61ED-4130-9A17-56526158EF80</a:ObjectID>
<a:Name>Group</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TypedCategoryTargetItem Id="o54">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>D4943B42-9F9F-4C2B-8DE3-7631391E4BAB</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o55">
<a:ObjectID>41DADF94-168E-4254-9D03-94D96C739780</a:ObjectID>
<a:Name>groupType</a:Name>
<a:TemplateTargetItem.Value>.if (%Reference%)
%Reference.groupType%
.elsif (%GroupParticle%)
%GroupParticle.groupType%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o56">
<a:ObjectID>12A26C33-8D8D-4344-AC97-3D2B835226B1</a:ObjectID>
<a:Name>itemReference</a:Name>
<a:TemplateTargetItem.Value>.if (%Reference%) and (%Reference.GroupParticle%)
%Reference.GroupParticle.itemReference%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o57">
<a:ObjectID>019167BD-CBFC-4900-B5A5-563DF011E414</a:ObjectID>
<a:Name>elementTypeDeclaration</a:Name>
<a:TemplateTargetItem.Value>.if (%GroupParticle%)
%GroupParticle.elementTypeDeclaration%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o58">
<a:ObjectID>3BEBC3F6-4234-4F35-AB5F-9EEBF581288D</a:ObjectID>
<a:Name>hasAny</a:Name>
<a:TemplateTargetItem.Value>.//check and return true if there is an Any elment child, otherwise return false
.if (%Reference%)
%Reference.hasAny%
.elsif (%GroupParticle%)
%GroupParticle.hasAny%
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o59">
<a:ObjectID>6480C92F-CB15-49F9-A2D4-083DEE4B5280</a:ObjectID>
<a:Name>description</a:Name>
<a:TemplateTargetItem.Value>.if (%Comment%) and (%GenOptions.generateComments%)
&lt;%xdrPrefix%description&gt;%.AX:Comment%&lt;/%xdrPrefix%description&gt;
.endif
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o60">
<a:ObjectID>D6B63045-BBE8-4076-8D12-F3456587D194</a:ObjectID>
<a:Name>maxOccursTemplate</a:Name>
<a:TemplateTargetItem.Value>.if (%MaxOccurs%)
   .if (%MaxOccurs% == &quot;unbounded&quot;)
maxOccurs=&quot;*&quot;
   .else
maxOccurs=&quot;%MaxOccurs%&quot;
   .endif
.endif
   
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o61">
<a:ObjectID>AB6F4076-19CF-4173-823D-87F2EF8FF2A9</a:ObjectID>
<a:Name>itemReferences</a:Name>
<a:TemplateTargetItem.Value>%itemReference%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o62">
<a:ObjectID>DC5A84BD-3DA5-427A-9405-292FC615C35A</a:ObjectID>
<a:Name>GroupParticle</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TypedCategoryTargetItem Id="o63">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>AE930565-B8C0-48CC-858E-B1F7014B76F8</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o64">
<a:ObjectID>929708A8-03F4-4AAB-BF3B-F3E1BA9320F0</a:ObjectID>
<a:Name>groupType</a:Name>
<a:TemplateTargetItem.Value>.// return the type of composition node : seq (stands for S), one (C) or many (A)
.if (%GroupType% == &quot;sequence&quot;)
seq
.elsif (%GroupType% == &quot;choice&quot;)
one
.elsif (%GroupType% == &quot;all&quot;)
many
.endif</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o65">
<a:ObjectID>3B0CDD1B-A79F-4A8E-8622-733F88A48083</a:ObjectID>
<a:Name>itemReferences</a:Name>
<a:TemplateTargetItem.Value>.foreach_item(Items)
%itemReference%
.next(\n)</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o66">
<a:ObjectID>359EEE64-60FA-4AB4-BD1A-1F45ECF8494A</a:ObjectID>
<a:Name>itemReference</a:Name>
<a:TemplateTargetItem.Value>.// look through the children of this group
&lt;%xdrPrefix%group[ minOccurs=&quot;%MinOccurs%&quot;][ %maxOccursTemplate%][ order=&quot;%groupType%&quot;]&gt;
   %itemReferences%
&lt;/%xdrPrefix%group&gt;
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o67">
<a:ObjectID>5E826B3F-415D-49FC-8221-1763CD4F56F9</a:ObjectID>
<a:Name>elementTypeDeclaration</a:Name>
<a:TemplateTargetItem.Value>.// for each items of this groupParticle, generate element Type declarations
.foreach_item(Items)
%elementTypeDeclaration%
.next(\n)</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o68">
<a:ObjectID>7E18D3FE-3B8A-4ECF-8774-3FD66020E356</a:ObjectID>
<a:Name>hasAny</a:Name>
<a:TemplateTargetItem.Value>.// check and return true if there is an Any element in the GroupParticle,
.// otherwise return null string (&quot;&quot;)
.set_value(_hasAny, &quot;&quot;, new)
.foreach_item(Items)
.if (%ObjectType% == &quot;Any&quot;)
.set_value(_hasAny, &quot;true&quot;, update)
.elsif (%ObjectType% == &quot;GroupParticle&quot;)
   .if (%hasAny%)
      .set_value(_hasAny, true, update)
   .endif
.endif
.next
%_hasAny%</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o69">
<a:ObjectID>7679D162-9A4D-45DF-A62F-98D11CA7F5C3</a:ObjectID>
<a:Name>maxOccursTemplate</a:Name>
<a:TemplateTargetItem.Value>.if (%MaxOccurs%)
   .if (%MaxOccurs% == &quot;unbounded&quot;)
maxOccurs=&quot;*&quot;
   .else
maxOccurs=&quot;%MaxOccurs%&quot;
   .endif
.endif
   
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o70">
<a:ObjectID>09D9534A-EB7B-4399-ABA9-00CDBEB1BDAD</a:ObjectID>
<a:Name>getNb</a:Name>
<a:TemplateTargetItem.Value>%Items.Count%
</a:TemplateTargetItem.Value>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o71">
<a:ObjectID>E94B644C-7C2F-4E05-84F3-994548567C3E</a:ObjectID>
<a:Name>SimpleType</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o72">
<a:ObjectID>5D4F0920-256D-4B34-9E57-3C71D8435870</a:ObjectID>
<a:Name>ComplexType</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o73">
<a:ObjectID>21F8B8EA-C253-4C7C-9A6A-B6CD0949DC94</a:ObjectID>
<a:Name>Annotation</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o74">
<a:ObjectID>BB3A97E0-9237-45C8-B9B1-EE58F44B0ED1</a:ObjectID>
<a:Name>Any</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TypedCategoryTargetItem Id="o75">
<a:TypePublicName>TemplateTargetItem</a:TypePublicName>
<a:ObjectID>6C1387FB-BCE2-466A-8BE6-78AE2ABEBD0D</a:ObjectID>
<a:Name>Templates</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TemplateTargetItem Id="o76">
<a:ObjectID>E68148B1-D081-44A1-A4D5-BAEF9857AD7F</a:ObjectID>
<a:Name>itemReference</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
<o:TemplateTargetItem Id="o77">
<a:ObjectID>9F69E259-B367-439A-8049-FF38AB535AA2</a:ObjectID>
<a:Name>elementTypeDeclaration</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
</o:TemplateTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o78">
<a:ObjectID>1F392FD7-3032-4B7F-8D90-CA8BBB573A3B</a:ObjectID>
<a:Name>Particle</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TypedCategoryTargetItem Id="o79">
<a:TypePublicName>CustomCheckTargetItem</a:TypePublicName>
<a:ObjectID>A8D8875F-8EAB-4B24-9004-603F789860A4</a:ObjectID>
<a:Name>Custom Checks</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:CustomCheckTargetItem Id="o80">
<a:ObjectID>E4FC04E9-7E5E-4C13-8F12-628A8E435DE9</a:ObjectID>
<a:Name>Invalid cardinality</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:HelpMessage>This check ensures that the MinOccurs is equal to 0 or 1 and the MaxOccurs is equal to 1 or unbounded.</a:HelpMessage>
<a:OutputMessage>The following Particles do not have a valid cardinality:</a:OutputMessage>
<a:CheckScript>Function %Check%(obj)
   %Check% = True
   if ((obj.MinOccurs &lt;&gt; &quot;&quot;) and (obj.MinOccurs &lt;&gt; &quot;0&quot;) and (obj.MinOccurs &lt;&gt; &quot;1&quot;)) then
      %Check% = False
   end if
   if ((obj.MaxOccurs &lt;&gt; &quot;&quot;) and (obj.MaxOccurs &lt;&gt; &quot;1&quot;) and (obj.MaxOccurs &lt;&gt; &quot;unbounded&quot;)) then
      %Check% = False   
   end if 
End Function</a:CheckScript>
<a:AutoFixScrpt>Function %Fix%(obj, outmsg)
   &#39; Implement your automatic correction on &lt;obj&gt; here
   &#39; filling &lt;outmsg&gt; as you which
   &#39; and return True if successful.

   outmsg = &quot;Automatic correction not implemented&quot;

   %Fix% = False
End Function</a:AutoFixScrpt>
</o:CustomCheckTargetItem>
</c:Categories>
</o:TypedCategoryTargetItem>
</c:Categories>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o81">
<a:ObjectID>1A808131-F021-43A6-99DA-5C5D5030FD11</a:ObjectID>
<a:Name>Entity</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o82">
<a:ObjectID>6D44169D-A882-41A9-A909-DA89E9741631</a:ObjectID>
<a:Name>Import</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o83">
<a:ObjectID>825ED1CF-DCF1-499E-84D3-F8C644294F62</a:ObjectID>
<a:Name>Include</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o84">
<a:ObjectID>DD11A2EF-A54B-4E6A-8A84-993F0AAA826D</a:ObjectID>
<a:Name>Redefine</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o85">
<a:ObjectID>C54AAC52-AFAD-4607-86ED-B49AC5749C39</a:ObjectID>
<a:Name>Key</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o86">
<a:ObjectID>DFB3E986-7538-4F56-BD8F-B55228A5CC56</a:ObjectID>
<a:Name>KeyRef</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o87">
<a:ObjectID>4E0C0CC0-9F09-49F3-9871-5BD3E8217F7D</a:ObjectID>
<a:Name>Unique</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
<o:MetaClassTargetItem Id="o88">
<a:ObjectID>98D899FE-AB34-4A08-AF04-0D8ED6472665</a:ObjectID>
<a:Name>Notation</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<a:ExcludeFromModel>1</a:ExcludeFromModel>
</o:MetaClassTargetItem>
</c:Categories>
</o:ProfileTargetItem>
<o:TargetCategory Id="o89">
<a:ObjectID>D1969A2D-1EB2-4258-A025-A688C1B4AF1B</a:ObjectID>
<a:Name>Settings</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:TargetCategory Id="o90">
<a:ObjectID>5300F4A7-F7CC-46C1-BA28-239E9835D4D4</a:ObjectID>
<a:Name>DataTypes</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:TargetCategory.Type>1</a:TargetCategory.Type>
<c:Categories>
<o:MapTargetItem Id="o91">
<a:ObjectID>003AE042-BFEE-41BA-BB3E-34F68E25B068</a:ObjectID>
<a:Name>ConceptualDataTypes</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:Comment>Conceptual Data Types</a:Comment>
<a:MapTargetItem.Value>A%n=string
VA%n=string
LA=string
LA%n=string
LVA=string
LVA%n=string
BT=i1
BT%n=bin.base64
SI=i2
I=int
LI=i4
N=float
N%n=number
N%s,%p=float
DC=float
DC%n=bin.base64
DC%s,%p=float
SF=r4
F=float
F%n=bin.base64
LF=r8
MN=float
MN%n=bin.base64
MN%s,%p=float
D=date
T=time
DT=dateTime
TS=time.tz
BL=boolean
NO=int
NO%n=bin.base64
BIN%n=bin.base64
LBIN=bin.base64
LBIN%n=bin.base64
TXT=string
TXT%n=string
MBT=string
MBT%n=string
VMBT=string
VMBT%n=string
PIC=bin.base64
PIC%n=bin.base64
BMP=bin.base64
BMP%n=bin.base64
OLE=bin.base64
OLE%n=bin.base64
*=string
ID=id
IDREF=idref
ENTITY=entity
ENTITIES=entities
NMTOKEN=nmtoken
NMTOKENS=nmtokens
IDREFS=idrefs
ANY=bin.base64</a:MapTargetItem.Value>
<a:List>A%n
VA%n
LA
LA%n
LVA
LVA%n
BT
BT%n
SI
I
LI
N
N%n
N%s,%p
DC
DC%n
DC%s,%p
SF
F
F%n
LF
MN
MN%n
MN%s,%p
D
T
DT
TS
BL
NO
NO%n
BIN%n
LBIN
LBIN%n
TXT
TXT%n
MBT
MBT%n
VMBT
VMBT%n
PIC
PIC%n
BMP
BMP%n
OLE
OLE%n
ID
IDREF
ENTITY
ENTITIES
NMTOKEN
NMTOKENS
IDREFS
ANY
</a:List>
</o:MapTargetItem>
<o:MapTargetItem Id="o92">
<a:ObjectID>C6C59332-E5F7-411F-B7C2-60E3B8510CCE</a:ObjectID>
<a:Name>XsmDataTypes</a:Name>
<a:CreationDate>0</a:CreationDate>
<a:Creator/>
<a:ModificationDate>0</a:ModificationDate>
<a:Modifier/>
<a:Comment>XSM Data Types</a:Comment>
<a:MapTargetItem.Value>i2=SI
i1=BT
i4=I
uuid=TXT
uri=TXT
ui4=LI
ui2=I
ui1=SI
r8=LF
r4=SF
boolean=BL
dateTime=DT
time.tz=TS
time=T
number=N
int=I
float=F
fixed.14.4=N14,4
dateTime.tz=DT
date=D
char=A1
bin.hex=BIN
bin.base64=BIN
string=TXT
idrefs=IDREFS
nmtokens=NMTOKENS
nmtoken=NMTOKEN
entities=ENTITIES
entity=ENTITY
enumeration=TXT
id=ID
idref=IDREF
notation=TXT</a:MapTargetItem.Value>
<a:List>i2
i1
i4
uuid
uri
ui4
ui2
ui1
r8
r4
boolean
dateTime
time.tz
time
number
int
float
fixed.14.4
dateTime.tz
date
char
bin.hex
bin.base64
string
idrefs
nmtokens
nmtoken
entities
entity
enumeration
id
idref
notation
</a:List>
</o:MapTargetItem>
</c:Categories>
</o:TargetCategory>
</c:Categories>
</o:TargetCategory>
</c:Categories>
</o:SchemaLanguage>

</SchemaLanguage>